### ISSUE TITLE
ValueError: Invalid foreground color: red

### ISSUE THREAD

**Issue by icyphox** [nbedos/termtosvg#1]
Hey, really cool project you've got there. Unfortunately for me, it crashes every time I try running it with the following traceback:
```
 Traceback (most recent call last):
  File "/home/icy/.local/bin/termtosvg", line 11, in <module>
    sys.exit(main())
  File "/home/icy/.local/lib/python3.6/site-packages/termtosvg/__main__.py", line 186, in main
    anim.render_animation(replayed_records, svg_filename)
  File "/home/icy/.local/lib/python3.6/site-packages/termtosvg/anim.py", line 208, in render_animation
    for event_record in record_group:
  File "/home/icy/.local/lib/python3.6/site-packages/termtosvg/term.py", line 268, in replay
    redraw_buffer[row][column] = from_pyte_char(screen.buffer[row][column], palette)
  File "/home/icy/.local/lib/python3.6/site-packages/termtosvg/anim.py", line 58, in from_pyte
    raise ValueError('Invalid foreground color: {}'.format(char.fg))
ValueError: Invalid foreground color: red
```
It happens just when I start typing something into the prompt, after running `termtosvg`.

**Comment by nbedos** [comment]
Hey! Sorry about that and thank you for opening an issue.

I was able to reproduce a similar crash when there are bright colors displayed on the terminal, but only the first 8 colors are defined in ~/.Xresources

I've released a new version to pypi which fixes this problem. Can you try it and let me know if it fixes the crash you're experiencing ?
```
pip install termtosvg==0.2.1
```
Thanks :)

**Comment by icyphox** [comment]
Yep, I can confirm that it's fixed now :)
Nice work.
Closing this issue.
