### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by Earnestly** [nbedos/termtosvg#2]
Hi, I've attempted to package termtosvg with the following versions in play:

* python 3.6.5
* python-svgwrite 1.1.12 (https://github.com/mozman/svgwrite/commit/5ce5ed51c094223043644bed7fd89e8d7ccdc91f)
* python-pyte 0.8.0
* python-xlib 0.23

However when attempting to run the command I am experiencing this error:

```
% termtosvg
Recording started, enter "exit" command or Control-D to end
Traceback (most recent call last):
  File "/usr/bin/termtosvg", line 11, in <module>
    load_entry_point('termtosvg==0.2.1', 'console_scripts', 'termtosvg')()
  File "/usr/lib/python3.6/site-packages/termtosvg/__main__.py", line 134, in main
    columns, lines, theme = term.get_configuration(output_fileno)
  File "/usr/lib/python3.6/site-packages/termtosvg/term.py", line 340, in get_configuration
    xresources_str = _get_xresources()
  File "/usr/lib/python3.6/site-packages/termtosvg/term.py", line 360, in _get_xresources
    return data.value.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by nbedos** [comment]
Hey man, thanks for the report.

I did not realize get_full_property from Xlib could return None. I've released a new version which should fix this crash:
```
pip install termtosvg==0.2.2
```

**Comment by Earnestly** [comment]
Seems good now, thanks
