### ISSUE TITLE
SyntaxError: invalid syntax ?

### ISSUE THREAD

**Issue by lrhazi** [nbedos/termtosvg#21]
```
scriptmgmt-2 :: ~ » termtosvg
Traceback (most recent call last):
  File "/usr/bin/termtosvg", line 11, in <module>
    load_entry_point('termtosvg==0.3.0', 'console_scripts', 'termtosvg')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/termtosvg/__main__.py", line 144
    print(record.to_json_line(), file=cast_file)
                                     ^
SyntaxError: invalid syntax
scriptmgmt-2 :: ~ 1 »
```

**Comment by RNabel** [comment]
While this is true, the executable placed on the path (`/usr/local/bin/termtosvg`) specified the interpreter `/usr/bin/python` which I then had to change to `#!/usr/bin/env python3`. 

Admittedly, I installed `termtosvg` using just `pip` which probably defaulted to `pip2`. @lrhazi changing this file may resolve your problem.

**Comment by nbedos** [comment]
Using `pip3 install termtosvg` is another solution. On some systems `pip` might default to `pip2.7` which is not compatible with termtosvg.
