### ISSUE TITLE
Running into this problem after pip install termtosvg

### ISSUE THREAD

**Issue by dmatrix** [nbedos/termtosvg#37]
I have python3 insalled and after installing termtosvg and trunning 'termtosvg,' I run into this syntax error. Any clues?

Traceback (most recent call last):
  File "/usr/local/bin/termtosvg", line 7, in <module>
    from termtosvg.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/termtosvg/__main__.py", line 144
    print(record.to_json_line(), file=cast_file)
                                     ^
SyntaxError: invalid syntax

**Comment by dmatrix** [comment]
Problem solved:

1. pip uninstall termtosvg
2. pip3 install termtosvg

By default pip, version2, uses python 2.7 in the startup file. Using pip3 install does the right thing.

**Comment by dmatrix** [comment]
Might want to document this to either have pip3 be in the default path, or explicitly specify to use pip3 install termtosvg, as part of the README.
