### ISSUE TITLE
README should mention that this is (currently?) Python 3 only

### ISSUE THREAD

**Issue by larsks** [nbedos/termtosvg#47]
Attempting to run `termtosvg` under python 2 will result in:

```
Traceback (most recent call last):
  File "/home/lars/src/termtosvg/.venv/bin/termtosvg", line 11, in <module>
    load_entry_point('termtosvg', 'console_scripts', 'termtosvg')()
  File "/home/lars/src/termtosvg/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/lars/src/termtosvg/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/home/lars/src/termtosvg/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/home/lars/src/termtosvg/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/lars/src/termtosvg/termtosvg/__main__.py", line 143
    print(record.to_json_line(), file=cast_file)
                                     ^
SyntaxError: invalid syntax
```

**Comment by nbedos** [comment]
Well, the README does mention that 'termtosvg is compatible with Python >= 3.5', but I could probably change it to 'termtosvg requires Python >= 3.5'.

And I doubt termtosvg will ever support Python 2.
