### ISSUE TITLE
KeyError: 12 text_color = palette[color_numbers[char.fg]]

### ISSUE THREAD

**Issue by Earnestly** [nbedos/termtosvg#48]
Hi again, after updating to https://github.com/nbedos/termtosvg/commit/464f5ea0012aa1b3df629788d6fa0ae819e53c75 I'm experiencing a new issue whenever I attempt to display any coloured output:
```
teapot earnest %i earnest ~ termtosvg -v foo.svg
Logging to /tmp/termtosvg_m7uxm9kd.log
Recording started, enter "exit" command or Control-D to end
teapot earnest %i earnest ~ ls -d study
study/
Traceback (most recent call last):
  File "/usr/bin/termtosvg", line 11, in <module>
    load_entry_point('termtosvg==0.4.0', 'console_scripts', 'termtosvg')()
  File "/usr/lib/python3.6/site-packages/termtosvg/__main__.py", line 194, in main
    anim.render_animation(replayed_records, svg_filename, font)
  File "/usr/lib/python3.6/site-packages/termtosvg/anim.py", line 213, in render_animation
    for event_record in record_group:
  File "/usr/lib/python3.6/site-packages/termtosvg/term.py", line 264, in replay
    redraw_buffer[row][column] = from_pyte_char(screen.buffer[row][column], palette)
  File "/usr/lib/python3.6/site-packages/termtosvg/anim.py", line 58, in from_pyte
    text_color = palette[color_numbers[char.fg]]
KeyError: 12
```

**Comment by nbedos** [comment]
Thanks for reporting the issue. It should be fixed by 5d8df03.
