### ISSUE TITLE
SyntaxError after Centos 7 installation

### ISSUE THREAD

**Issue by wittmaha** [nbedos/termtosvg#64]
Hi guys,

i get following error on Centos 7.  Could you please tell my why?

```
Traceback (most recent call last):
  File "/home/xxxxxx/.local/bin/termtosvg", line 11, in <module>
    load_entry_point('termtosvg==0.4.0', 'console_scripts', 'termtosvg')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/xxxxxx/.local/lib/python2.7/site-packages/termtosvg/__main__.py", line 143
    print(record.to_json_line(), file=cast_file)
                                     ^
SyntaxError: invalid syntax
```

THANKS

Greets

Harry

**Comment by nnist** [comment]
I think this is because you're using Python 2.7, the readme says termtosvg requires Python >= 3.5.

**Comment by nbedos** [comment]
> I think this is because you're using Python 2.7, the readme says termtosvg requires Python >= 3.5.
Exactly!

**Comment by wittmaha** [comment]
Ah, sorry guys and thank you for the hint.
