### ISSUE TITLE
AttributeError: readonly attribute

### ISSUE THREAD

**Issue by xAiLx** [nbedos/termtosvg#68]
[user@web ~]$ termtosvg
Traceback (most recent call last):
  File "/home/user/.local/bin/termtosvg", line 7, in <module>
    from termtosvg.__main__ import main
  File "/home/user/.local/lib/python3.4/site-packages/termtosvg/__main__.py", line 8, in <module>
    import termtosvg.anim as anim
  File "/home/user/.local/lib/python3.4/site-packages/termtosvg/anim.py", line 27, in <module>
    _CharacterCell.text.__doc__ = 'Text content of the cell'
AttributeError: readonly attribute

**Comment by nbedos** [comment]
As stated in the readme, termtosvg requires Python >= 3.5
