### ISSUE TITLE
TypeError: set_margins & quits when running mc (Midnight Commander)

### ISSUE THREAD

**Issue by edrozenberg** [nbedos/termtosvg#81]
Running mc on MacOS default terminal (Mojave), Python 3.7.1. After running then quitting mc (F10), I see the following errors and termtosvg session has quit/exited (and a blank .svg file was written to /var/....)

```
Traceback (most recent call last):
  File "/usr/local/bin/termtosvg", line 6, in <module> termtosvg.main.main()
  File "/usr/local/lib/python3.7/site-packages/termtosvg/main.py", line 229, in main svg_filename, args.min_frame_duration, args.max_frame_duration)
  File "/usr/local/lib/python3.7/site-packages/termtosvg/main.py", line 188, in record_render_subcommand template=template)
  File "/usr/local/lib/python3.7/site-packages/termtosvg/anim.py", line 280, in render_animation root = _render_animation(records, template, cell_width, cell_height)
  File "/usr/local/lib/python3.7/site-packages/termtosvg/anim.py", line 397, in _render_animation defs=definitions)
  File "/usr/local/lib/python3.7/site-packages/termtosvg/anim.py", line 223, in make_animated_group for event_record in records:
  File "/usr/local/lib/python3.7/site-packages/termtosvg/term.py", line 242, in replay stream.feed(event_record.event_data)
  File "/usr/local/lib/python3.7/site-packages/pyte/streams.py", line 395, in feed super(ByteStream, self).feed(data)
  File "/usr/local/lib/python3.7/site-packages/pyte/streams.py", line 196, in feed taking_plain_text = send(data[offset:offset + 1])
  File "/usr/local/lib/python3.7/site-packages/pyte/streams.py", line 324, in _parser_fsm csi_dispatch[char](*params, private=True)
TypeError: set_margins() got an unexpected keyword argument 'private'
```

**Comment by nbedos** [comment]
Thanks for reporting the issue.

termtosvg uses Pyte for rendering the terminal screen and Pyte expects the `TERM` environment variable to be set to `linux` (https://github.com/selectel/pyte/issues/67). If `TERM` is set to something else your command line utilities might produce output that Pyte cannot understand which would cause a crash. It seems to be quite rare though, I've never encountered this bug before.

You can try starting termtosvg this way to see if changing this variable fixes the problem:
```
$ TERM=linux termtosvg
```
Let me know if it works.

**Comment by nbedos** [comment]
I'm closing this issue since it's been inactive for 9 days. If you're experiencing the same problem and the solution described above does not work, leave a message and I'll reopen the issue.

**Comment by edrozenberg** [comment]
Thanks! ```$ TERM=linux termtosvg``` seems to fix the problem.

This is in Mac, where normally the following is set (which always causes the problem):
```
declare -x TERM="xterm-256color"
declare -x TERM_PROGRAM="Apple_Terminal"
declare -x TERM_PROGRAM_VERSION="421.1"
```
