### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2764' in position 219: ordinal not in range(128)

### ISSUE THREAD

**Issue by nmattia** [nbedos/termtosvg#91]
When building `termtosvg` using Nix:

```
======================================================================
ERROR: test_main (termtosvg.tests.test_main.TestMain) (case='render v1 cast file')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/termtosvg/tests/test_main.py", line 171, in test_main
    cast_file.write(cast_v1_data)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2764' in position 219: ordinal not in range(128)

======================================================================
ERROR: test_main (termtosvg.tests.test_main.TestMain) (case='render v1 cast file')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/termtosvg/tests/test_main.py", line 171, in test_main
    cast_file.write(cast_v1_data)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2764' in position 219: ordinal not in range(128)

----------------------------------------------------------------------
Ran 54 tests in 13.824s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=54 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=54 errors=2 failures=0>
```
here's the nix invocation:

```
  termtosvg =
    python3.pkgs.buildPythonApplication rec {
      pname = "termtosvg";
      version = "0.8.0";
      doCheck = false;

      # tests are not available when fetching from pypi
      src = sources.termtosvg;

      propagatedBuildInputs = with python3.pkgs; [ lxml pyte ];

      meta = with lib; {
        inherit (sources.termtosvg) homepage description;
        license = licenses.bsd3;
        maintainers = with maintainers; [ ma27 ];
      };
    };
```

here are the versions used:

```
Package: nixpkgs
  url: https://github.com/NixOS/nixpkgs-channels/archive/9bd45dddf8171e2fd4288d684f4f70a2025ded19.tar.gz
  owner: NixOS
  branch: nixos-18.09
  url_template: https://github.com/<owner>/<repo>/archive/<rev>.tar.gz
  repo: nixpkgs-channels
  sha256: 1idrxrymwqfsfysav3yl8lya1jhgg8xzgq9hy7dpdd63770vn8c1
  description: Nixpkgs/NixOS branches that track the Nixpkgs/NixOS channels
  rev: 9bd45dddf8171e2fd4288d684f4f70a2025ded19
Package: termtosvg
  homepage: https://nbedos.github.io/termtosvg/
  url: https://github.com/nbedos/termtosvg/archive/8e4b26914866f43da829bf33e4a7aee0e60035da.tar.gz
  owner: nbedos
  branch: develop
  url_template: https://github.com/<owner>/<repo>/archive/<rev>.tar.gz
  repo: termtosvg
  sha256: 000wyddlw4isxqlha7xa62dwp7gv12g90s825bgahyr26dy7wkrb
  description: Record terminal sessions as SVG animations
  rev: 8e4b26914866f43da829bf33e4a7aee0e60035da
```

**Comment by nbedos** [comment]
The step causing the exception is basically just writing a string that contains non ascii characters to a file. Does the following crash too ?
```python
s = "❤ ☀ ☆ ☂ ☻ ♞ ☯ ☭ ☢ € →"
with open('/tmp/termtosvg.txt', 'w') as f:
    f.write(s)
```
Any chance these tests could have been run by a Python 2 interpreter ?

By the way:
>       # tests are not available when fetching from pypi
They are now, no need to grab the source anymore! Just run `python -m unittest termtosvg.tests.suite`

**Comment by nmattia** [comment]
It appears to be working fine now! Must have been an issue in nixpkgs. Thanks for looking into this!
